### ISSUE TITLE
Add loaders and transition effects.

### ISSUE THREAD

**Issue by kamiri-charles** [kamiri-charles/notes-app#3]

**Comment by boomboss200** [comment]
where do you want the loaders to be added? when fetching the notes data from the backend ?

also I would like to work on the loaders part

**Comment by kamiri-charles** [comment]
Hi, @boomboss200, yes I want a loader after fetching data from the backend. I haven't yet hosted the backend yet (working on it currently...) so it might have to wait. Hopefully the backend will be live after a few hours. I will add the api links and you'll be able to work on it.

**Comment by boomboss200** [comment]
Alright, I will get back at it tomorrow, to get this issue solved

**Comment by kamiri-charles** [comment]
Hey @boomboss200 , there's a test_user account for development purposes. 
Username: 'test_account'
Password: '12345'


There's still a lot to do with the UI and the backend so the app might not run optimally.

**Comment by boomboss200** [comment]
okey got It. thanks for providing that

**Comment by boomboss200** [comment]
the sign in button when pressed doesnt do anything for some reason even after providing the test username and password given. @kamiri-charles can you please double check is it working ?
also I have done 
nom install and nom start to run the project

**Comment by kamiri-charles** [comment]
@boomboss200 Let me check it out

**Comment by kamiri-charles** [comment]
Hey @boomboss200 , I fixed the issue and created a new dev account. 
Username: test_user
Password: 12345

**Comment by boomboss200** [comment]
@kamiri-charles added the loaders you can see from the screenshot attach , if you want to change the loader style let me know also if you want to add the Loader to appear in more areas than just fetching notes .also do let me know
![Screenshot 2023-02-09 at 3 49 51 AM](https://user-images.githubusercontent.com/98022071/217805019-1d3f2b22-d103-4e53-a24c-4f0c4f353f8d.png)

**Comment by kamiri-charles** [comment]
Awesome...
