### ISSUE TITLE
Username not showing on the header after sign-in/sign-up. Only showing up after refresh.

### ISSUE THREAD

**Issue by kamiri-charles** [kamiri-charles/notes-app#7]

**Comment by nelliott82** [comment]
@kamiri-charles I believe I have this fixed.

**Comment by kamiri-charles** [comment]
@nelliott82 go for it...

**Comment by nelliott82** [comment]
@kamiri-charles I apologize, but I'm new to contributing to open source projects. How do I gain permission?

**Comment by kamiri-charles** [comment]
@nelliott82  You don't really need persmission, since the repo is public, you can just fork the code and then make changes the add a pull request with the requested changes. I'll then review the changes and merge them into the project.

After forking, run `npm i` to install the required dependecies for the project and then run `npm start` to start the project in a dev server `localhost:3000`.

**Comment by nelliott82** [comment]
@kamiri-charles On further examination, I have A fix, but maybe not THE fix.

Essentially, the problem boils down to the Header element being outside the Routes. When navigating to different routes, Header doesn't automatically refresh.

I included Header as a second element when navigating to '/' and it works, but then the dom has two Header elements. Not ideal. Let me know if you want me to go ahead with that fix.

**Comment by kamiri-charles** [comment]
@nelliott82 Well, I agree it's not ideal but if it works, it'll have to be THE fix for now. Just open a pull request.
